#!/bin/sh

# grade - grade the numeric argument using the followiong bands
# A 80 - 100
# B 60 - 79
# C 30 - 59
# D 10 - 29
# E 0  - 9

if [  $# != 1 ]
then
   echo "usage: grade percentage-grade"
   exit 1
fi

Grade=$1;

if [ $Grade -le 0 ]
then
  echo "Percentage grade < 0 - error"
  exit 1
elif [ $Grade -le 9 ]
then
  echo "E"
elif [ $Grade -le 29 ]
then
  echo "D"
elif [ $Grade -le 59 ]
then
  echo "C"
elif [ $Grade -le 79 ]
then
  echo "B"
elif [ $Grade -le 100 ]
then
  echo "A"
else
   echo "Percentage grade > 100 - error"
   exit 1
fi


exit 0
